version: '3.8'
name: golang-ca
services:
  redis:
    container_name: redis-goapi-ca-rest
    image: redis:6.2-alpine
    env_file: .env
    command: redis-server
    restart: on-failure
    ports:
      - 6379:6379

  postgres:
    container_name: postgres-goapi-ca-rest
    image: postgres
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${DB_MAIN}
    ports:
      - 5432:5432
    volumes:
      - ./commands/db/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./pgdata:/var/lib/postgresql/data
    restart: on-failure
