version: '3.8'
services:
  redis:
    container_name: redis-goapi-ca-rest
    image: redis:6.2-alpine
    env_file: .docker.env
    command: redis-server
    restart: on-failure
    ports:
      - 6379:6379

  postgres:
    container_name: postgres-goapi-ca-rest
    image: postgres
    env_file: .docker.env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tempest1!
      POSTGRES_DB: Tempest1!
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/data
    restart: on-failure
